// <auto-generated>This is auto-generated code by a DIS Macro. Do not modify.</auto-generated>
namespace Skyline.Protocol.Tables
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net.Helper;
	using Skyline.DataMiner.Scripting;

	using SLNetMessages = Skyline.DataMiner.Net.Messages;

	public class MembersTableRow
	{
		public MembersTableRow() { }

		public MembersTableRow(params object[] row)
		{
			Instance = Convert.ToString(row[0]);
			Id = Convert.ToInt64(row[1]);
			Login = Convert.ToString(row[2]);
			Type = Convert.ToString(row[3]);
			SiteAdmin = Convert.ToBoolean(Convert.ToInt16(row[4]));
			Url = Convert.ToString(row[5]);
			HtmlUrl = Convert.ToString(row[6]);
			AvatarUrl = Convert.ToString(row[7]);
		}

		public string Instance { get; set; } = Exceptions.NotAvailable;

		public long Id { get; set; }

		public string Login { get; set; }

		public string Type { get; set; }

		public bool SiteAdmin { get; set; }

		public string Url { get; set; }

		public string HtmlUrl { get; set; }

		public string AvatarUrl { get; set; }

		public static MembersTableRow FromPK(SLProtocol protocol, string pk)
		{
			var row = (object[])protocol.GetRow(Parameter.Organizationmembers.tablePid, pk);
			if (row[0] == null)
			{
				return default;
			}

			return new MembersTableRow(row);
		}

		public object[] ToProtocolRow()
		{
			return new OrganizationmembersQActionRow
			{
				Organizationmembersinstance_3601 = Instance,
				Organizationmembersid_3602 = Id,
				Organizationmemberslogin_3603 = Login,
				Organizationmemberstype_3604 = Type,
				Organizationmemberssiteadmin_3605 = Convert.ToInt16(SiteAdmin),
				Organizationmembersurl_3606 = Url,
				Organizationmembershtmlurl_3607 = HtmlUrl,
				Organizationmembersavatarurl_3608 = AvatarUrl,
			};
		}

		public void SaveToProtocol(SLProtocol protocol)
		{
			if (!protocol.Exists(Parameter.Organizationmembers.tablePid, Instance))
			{
				protocol.AddRow(Parameter.Organizationmembers.tablePid, ToProtocolRow());
			}
			else
			{
				protocol.SetRow(Parameter.Organizationmembers.tablePid, Instance, ToProtocolRow());
			}
		}
	}

	public class MembersTable
	{
		private static MembersTable instance = new MembersTable();

		public MembersTable() { }

		public MembersTable(SLProtocol protocol)
		{
			uint[] organizationMembersIdx = new uint[]
			{
				Parameter.Organizationmembers.Idx.organizationmembersinstance_3601,
				Parameter.Organizationmembers.Idx.organizationmembersid_3602,
				Parameter.Organizationmembers.Idx.organizationmemberslogin_3603,
				Parameter.Organizationmembers.Idx.organizationmemberstype_3604,
				Parameter.Organizationmembers.Idx.organizationmemberssiteadmin_3605,
				Parameter.Organizationmembers.Idx.organizationmembersurl_3606,
				Parameter.Organizationmembers.Idx.organizationmembershtmlurl_3607,
				Parameter.Organizationmembers.Idx.organizationmembersavatarurl_3608,
			};
			object[] members = (object[])protocol.NotifyProtocol((int)SLNetMessages.NotifyType.NT_GET_TABLE_COLUMNS, Parameter.Organizationmembers.tablePid, organizationMembersIdx);
			object[] instance = (object[])members[0];
			object[] id = (object[])members[1];
			object[] login = (object[])members[2];
			object[] type = (object[])members[3];
			object[] siteAdmin = (object[])members[4];
			object[] url = (object[])members[5];
			object[] htmlUrl = (object[])members[6];
			object[] avatarUrl = (object[])members[7];

			for (int i = 0; i < instance.Length; i++)
			{
				Rows.Add(new MembersTableRow(
				instance[i],
				id[i],
				login[i],
				type[i],
				siteAdmin[i],
				url[i],
				htmlUrl[i],
				avatarUrl[i]));
			}
		}

		public List<MembersTableRow> Rows { get; set; } = new List<MembersTableRow>();

		public static MembersTable GetTable(SLProtocol protocol = null)
		{
			if (protocol != null)
			{
				instance = new MembersTable(protocol);
			}

			return instance;
		}

		public void SaveToProtocol(SLProtocol protocol, bool partial = false)
		{
			// Calculate the batch size, recommended 25000 cells max per fill array, divided by the number of columns.
			var batchSize = 25000 / 8;

			// If full then the first batch needs to be a SaveOption.Full.
			var first = !partial;
			if (!Rows.Any() && !partial)
			{
				protocol.ClearAllKeys(Parameter.Organizationmembers.tablePid);
				return;
			}

			foreach (var batch in Rows.Select(x => x.ToProtocolRow()).Batch(batchSize))
			{
				if (first)
				{
					protocol.FillArray(Parameter.Organizationmembers.tablePid, batch.ToList(), NotifyProtocol.SaveOption.Full);
				}
				else
				{
					protocol.FillArray(Parameter.Organizationmembers.tablePid, batch.ToList(), NotifyProtocol.SaveOption.Partial);
				}
			}
		}
	}
}
