// <auto-generated>This is auto-generated code by a DIS Macro. Do not modify.</auto-generated>
namespace Skyline.Protocol.Tables
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net.Helper;
	using Skyline.DataMiner.Scripting;
	using Skyline.DataMiner.Utils.Github.API.V20221128.Repositories;
	using Skyline.Protocol.Extensions;

	using SLNetMessages = Skyline.DataMiner.Net.Messages;

	public class ReleaseAssetsTableRow
	{
		private static readonly double DateTimeNotAvailable = -2;

		private string label;
		private DateTime createdAt;
		private DateTime updatedAt;

		public ReleaseAssetsTableRow() { }

		public ReleaseAssetsTableRow(params object[] row)
		{
			Instance = Convert.ToString(row[0]);
			AssetId = Convert.ToInt64(row[1]);
			RepositoryID = Convert.ToString(row[2]);
			Release = Convert.ToString(row[3]);
			Uploader = Convert.ToString(row[4]);
			NodeID = Convert.ToString(row[5]);
			Name = Convert.ToString(row[6]);
			label = Convert.ToString(row[7]);
			ContentType = Convert.ToString(row[8]);
			State = Convert.ToString(row[9]);
			Size = Convert.ToInt64(row[10]);
			DownloadCount = Convert.ToInt64(row[11]);
			CreatedAt = DateTime.FromOADate(Convert.ToDouble(row[12]));
			UpdatedAt = DateTime.FromOADate(Convert.ToDouble(row[13]));
			BrowserDownloadUrl = Convert.ToString(row[14]);
		}

		public string Instance { get; set; }

		public long AssetId { get; set; }

		public string RepositoryID { get; set; }

		public string Release { get; set; }

		public string Uploader { get; set; }

		public string NodeID { get; set; }

		public string Name { get; set; }

		public string Label
		{
			get
			{
				if(label == Exceptions.NotAvailable)
				{
					return null;
				}

				return label;
			}

			set
			{
				if(value == null || value == Exceptions.NotAvailable)
				{
					label = Exceptions.NotAvailable;
				}
				else
				{
					label = value;
				}
			}
		}

		public string ContentType { get; set; }

		public string State { get; set; }

		public long Size { get; set; }

		public long DownloadCount { get; set; }

		public DateTime CreatedAt
		{
			get
			{
				return createdAt;
			}

			set
			{
				createdAt = value;
			}
		}

		public double CreatedAtOA
		{
			get
			{
				if (createdAt == default)
				{
					return DateTimeNotAvailable;
				}

				return createdAt.ToOADate();
			}
		}

		public DateTime UpdatedAt
		{
			get
			{
				return updatedAt;
			}

			set
			{
				updatedAt = value;
			}
		}

		public double UpdatedAtOA
		{
			get
			{
				if (updatedAt == default)
				{
					return DateTimeNotAvailable;
				}

				return updatedAt.ToOADate();
			}
		}

		public string BrowserDownloadUrl { get; set; }

		public static ReleaseAssetsTableRow FromPK(SLProtocol protocol, string pk)
		{
			var row = (object[])protocol.GetRow(Parameter.Repositoryreleaseassets.tablePid, pk);
			if (row[0] == null)
			{
				return default;
			}

			return new ReleaseAssetsTableRow(row);
		}

		public object[] ToProtocolRow()
		{
			return new RepositoryreleaseassetsQActionRow
			{
				Repositoryreleaseassetsinstance_1801 = Instance,
				Repositoryreleaseassetsid_1802 = AssetId,
				Repositoryreleaseassetsrepositoryid_1803 = RepositoryID,
				Repositoryreleaseassetsrelease_1804 = Release,
				Repositoryreleaseassetsuploader_1805 = Uploader,
				Repositoryreleaseassetsnodeid_1806 = NodeID,
				Repositoryreleaseassetsname_1807 = Name,
				Repositoryreleaseassetslabel_1808 = Label,
				Repositoryreleaseassetscontenttype_1809 = ContentType,
				Repositoryreleaseassetsstate_1810 = State,
				Repositoryreleaseassetssize_1811 = Size,
				Repositoryreleaseassetsdownloadcount_1812 = DownloadCount,
				Repositoryreleaseassetscreatedat_1813 = CreatedAtOA,
				Repositoryreleaseassetsupdatedat_1814 = UpdatedAtOA,
				Repositoryreleaseassetsbrowserdownloadurl_1815 = BrowserDownloadUrl,
			};
		}

		public void SaveToProtocol(SLProtocol protocol)
		{
			if (!protocol.Exists(Parameter.Repositoryreleaseassets.tablePid, Instance))
			{
				protocol.AddRow(Parameter.Repositoryreleaseassets.tablePid, ToProtocolRow());
			}
			else
			{
				protocol.SetRow(Parameter.Repositoryreleaseassets.tablePid, Instance, ToProtocolRow());
			}
		}
	}

	public class ReleaseAssetsTable : IDisposable
	{
		private static ReleaseAssetsTable instance = new ReleaseAssetsTable();

		public ReleaseAssetsTable()
		{
			RepositoriesTable.RepositoriesChanged += RepositoriesTable_RepositoriesChanged;
		}

		public ReleaseAssetsTable(SLProtocol protocol)
		{
			RepositoriesTable.RepositoriesChanged += RepositoriesTable_RepositoriesChanged;

			uint[] repositoryReleaseAssetsIdx = new uint[]
			{
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsinstance_1801,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsid_1802,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsrepositoryid_1803,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsrelease_1804,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsuploader_1805,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsnodeid_1806,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsname_1807,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetslabel_1808,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetscontenttype_1809,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsstate_1810,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetssize_1811,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsdownloadcount_1812,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetscreatedat_1813,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsupdatedat_1814,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsbrowserdownloadurl_1815,
			};
			object[] releaseassets = (object[])protocol.NotifyProtocol((int)SLNetMessages.NotifyType.NT_GET_TABLE_COLUMNS, Parameter.Repositoryreleaseassets.tablePid, repositoryReleaseAssetsIdx);
			object[] instance = (object[])releaseassets[0];
			object[] assetID = (object[])releaseassets[1];
			object[] repositoryID = (object[])releaseassets[2];
			object[] release = (object[])releaseassets[3];
			object[] uploader = (object[])releaseassets[4];
			object[] nodeID = (object[])releaseassets[5];
			object[] name = (object[])releaseassets[6];
			object[] label = (object[])releaseassets[7];
			object[] contentType = (object[])releaseassets[8];
			object[] state = (object[])releaseassets[9];
			object[] size = (object[])releaseassets[10];
			object[] downloadCount = (object[])releaseassets[11];
			object[] createdAt = (object[])releaseassets[12];
			object[] updatedAt = (object[])releaseassets[13];
			object[] browserDownloadUrl = (object[])releaseassets[14];

			for (int i = 0; i < instance.Length; i++)
			{
				Rows.Add(new ReleaseAssetsTableRow(
				instance[i],
				assetID[i],
				repositoryID[i],
				release[i],
				uploader[i],
				nodeID[i],
				name[i],
				label[i],
				contentType[i],
				state[i],
				size[i],
				downloadCount[i],
				createdAt[i],
				updatedAt[i],
				browserDownloadUrl[i]));
			}
		}
		
		public List<ReleaseAssetsTableRow> Rows { get; set; } = new List<ReleaseAssetsTableRow>();

		public static ReleaseAssetsTable GetTable(SLProtocol protocol = null)
		{
			if (protocol != null)
			{
				instance.Dispose();
				instance = new ReleaseAssetsTable(protocol);
			}

			return instance;
		}

		public void DeleteRow(SLProtocol protocol, params string[] rowsToDelete)
		{
			if (rowsToDelete.Length <= 0)
				return;

			// Remove from DateMiner and local instance
			protocol.DeleteRow(Parameter.Repositoryreleaseassets.tablePid, rowsToDelete);
			instance.Rows.RemoveAll(x => rowsToDelete.ToList().Contains(x.Instance));
		}

		public void SaveToProtocol(SLProtocol protocol, bool partial = false)
		{
			// Calculate the batch size, recommended 25000 cells max per fill array, divided by the number of columns.
			var batchSize = 25000 / 14;

			// When full updating and the Rows are empty, clear the table.
			if (!Rows.Any() && !partial)
			{
				protocol.ClearAllKeys(Parameter.Repositoryreleaseassets.tablePid);
				return;
			}

			// If full then the first batch needs to be a SaveOption.Full.
			var first = !partial;
			foreach (var batch in Rows.Select(x => x.ToProtocolRow()).Batch(batchSize))
			{
				if (first)
				{
					protocol.FillArray(Parameter.Repositoryreleaseassets.tablePid, batch.ToList(), NotifyProtocol.SaveOption.Full);
				}
				else
				{
					protocol.FillArray(Parameter.Repositoryreleaseassets.tablePid, batch.ToList(), NotifyProtocol.SaveOption.Partial);
				}
			}
		}

		private void RepositoriesTable_RepositoriesChanged(object sender, RepositoryEventArgs e)
		{
			// There only needs to happen something when removing a repository
			if (e.Type != RepositoryChange.Remove)
				return;

			// Delete Linked Release Assets
			var releasesIdx = new uint[]
			{
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsinstance,
				Parameter.Repositoryreleaseassets.Idx.repositoryreleaseassetsrepositoryid,
			};

			var assetRows = ((object[])e.Protocol.NotifyProtocol((int)SLNetMessages.NotifyType.NT_GET_TABLE_COLUMNS, Parameter.Repositoryreleaseassets.tablePid, releasesIdx))
				.Select(col => Array.ConvertAll((object[])col, Convert.ToString))
				.ToRows()
				.Where(row => e.Repositories.Contains(row[1]))
				.Select(row => row[0]);

			ReleaseAssetsTable.GetTable().DeleteRow(e.Protocol, assetRows.ToArray());
		}

		#region IDisposable
		public void Dispose()
		{
			// Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		protected virtual void Dispose(bool disposing)
		{
			RepositoriesTable.RepositoriesChanged -= RepositoriesTable_RepositoriesChanged;
		}
		#endregion
	}
}
