// <auto-generated>This is auto-generated code by a DIS Macro. Do not modify.</auto-generated>
namespace Skyline.Protocol.Tables
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Linq;

	using Skyline.DataMiner.Net.Helper;
	using Skyline.DataMiner.Scripting;

	using SLNetMessages = Skyline.DataMiner.Net.Messages;
	using Extensions = Skyline.Protocol.Extensions.Extensions;
	using Skyline.Protocol.Extensions;

	public enum PrivacySetting
	{
		[Description("closed")]
		Closed,

		[Description("secret")]
		Secret,
	}

	public enum NotificationSetting
	{
		[Description("notifications_enabled")]
		Enabled,

		[Description("notifications_disabled")]
		Disabled,
	}

	public class TeamsTableRow
	{
		public TeamsTableRow() { }

		public TeamsTableRow(params object[] row)
		{
			Instance = Convert.ToString(row[0]);
			Id = Convert.ToInt64(row[1]);
			Organization = Convert.ToString(row[2]);
			Name = Convert.ToString(row[3]);
			Slug = Convert.ToString(row[4]);
			Description = Convert.ToString(row[5]);
			Privacy = Extensions.ParseEnumDescription<PrivacySetting>(Convert.ToString(row[6]));
			NotificationsEnabled = Extensions.ParseEnumDescription<NotificationSetting>(Convert.ToString(row[7])); ;
			Permission = Convert.ToString(row[8]);
		}

		public string Instance { get; set; } = Exceptions.NotAvailable;

		public long Id { get; set; }

		public string Organization { get; set; }

		public string Name { get; set; }

		public string Slug { get; set; }

		public string Description { get; set; }

		public PrivacySetting Privacy { get; set; }

		public NotificationSetting NotificationsEnabled { get; set; }

		public string Permission { get; set; }

		public static TeamsTableRow FromPK(SLProtocol protocol, string pk)
		{
			var row = (object[])protocol.GetRow(Parameter.Organizationteams.tablePid, pk);
			if (row[0] == null)
			{
				return default;
			}

			return new TeamsTableRow(row);
		}

		public object[] ToProtocolRow()
		{
			return new OrganizationteamsQActionRow
			{
				Organizationteamsinstance = Instance,
				Organizationteamsid = Id,
				Organizationteamsorganization = Organization,
				Organizationteamsname = Name,
				Organizationteamsslug = Slug,
				Organizationteamsdescription = Description,
				Organizationteamsprivacy = Privacy.FriendlyDescription(),
				Organizationteamsnotificationsenabled = NotificationsEnabled.FriendlyDescription(),
				Organizationteamspermission = Permission,
			};
		}

		public void SaveToProtocol(SLProtocol protocol)
		{
			if (!protocol.Exists(Parameter.Organizationteams.tablePid, Instance))
			{
				protocol.AddRow(Parameter.Organizationteams.tablePid, ToProtocolRow());
			}
			else
			{
				protocol.SetRow(Parameter.Organizationteams.tablePid, Instance, ToProtocolRow());
			}
		}
	}

	public class TeamsTable
	{
		private static TeamsTable instance = new TeamsTable();

		public TeamsTable() { }

		public TeamsTable(SLProtocol protocol)
		{
			uint[] organizationTeamsIdx = new uint[]
			{
				Parameter.Organizationteams.Idx.organizationteamsinstance,
				Parameter.Organizationteams.Idx.organizationteamsid,
				Parameter.Organizationteams.Idx.organizationteamsorganization,
				Parameter.Organizationteams.Idx.organizationteamsname,
				Parameter.Organizationteams.Idx.organizationteamsslug,
				Parameter.Organizationteams.Idx.organizationteamsdescription,
				Parameter.Organizationteams.Idx.organizationteamsprivacy,
				Parameter.Organizationteams.Idx.organizationteamsnotificationsenabled,
				Parameter.Organizationteams.Idx.organizationteamspermission,
			};
			object[] teams = (object[])protocol.NotifyProtocol((int)SLNetMessages.NotifyType.NT_GET_TABLE_COLUMNS, Parameter.Organizationteams.tablePid, organizationTeamsIdx);
			object[] instance = (object[])teams[0];
			object[] id = (object[])teams[1];
			object[] organization = (object[])teams[2];
			object[] name = (object[])teams[3];
			object[] slug = (object[])teams[4];
			object[] description = (object[])teams[5];
			object[] privacy = (object[])teams[6];
			object[] notificationsEnabled = (object[])teams[7];
			object[] permission = (object[])teams[8];

			for (int i = 0; i < instance.Length; i++)
			{
				Rows.Add(new TeamsTableRow(
				instance[i],
				id[i],
				organization[i],
				name[i],
				slug[i],
				description[i],
				privacy[i],
				notificationsEnabled[i],
				permission[i]));
			}
		}

		public List<TeamsTableRow> Rows { get; set; } = new List<TeamsTableRow>();

		public static TeamsTable GetTable(SLProtocol protocol = null)
		{
			if (protocol != null)
			{
				instance = new TeamsTable(protocol);
			}

			return instance;
		}

		public void SaveToProtocol(SLProtocol protocol, bool partial = false)
		{
			// Calculate the batch size, recommended 25000 cells max per fill array, divided by the number of columns.
			var batchSize = 25000 / 9;

			// If full then the first batch needs to be a SaveOption.Full.
			var first = !partial;
			if (!Rows.Any() && !partial)
			{
				protocol.ClearAllKeys(Parameter.Organizationteams.tablePid);
				return;
			}

			foreach (var batch in Rows.Select(x => x.ToProtocolRow()).Batch(batchSize))
			{
				if (first)
				{
					protocol.FillArray(Parameter.Organizationteams.tablePid, batch.ToList(), NotifyProtocol.SaveOption.Full);
				}
				else
				{
					protocol.FillArray(Parameter.Organizationteams.tablePid, batch.ToList(), NotifyProtocol.SaveOption.Partial);
				}
			}
		}
	}
}

