// <auto-generated>This is auto-generated code by a DIS Macro. Do not modify.</auto-generated>
namespace Skyline.Protocol.Tables
{
	using System;
	using System.Collections.Generic;
	using System.Linq;

	using Skyline.DataMiner.Net.Helper;
	using Skyline.DataMiner.Scripting;
	using Skyline.Protocol.PollManager;
	using Skyline.Protocol.Tables.Events;

	using SLNetMessages = Skyline.DataMiner.Net.Messages;

	public class MemberOrganizationLinksTableRow
	{
		private static readonly double DateTimeNotAvailable = -2;

		private DateTime lastPolledAt;

		public MemberOrganizationLinksTableRow() { }

		public MemberOrganizationLinksTableRow(params object[] row)
		{
			Instance = Convert.ToString(row[0]);
			Organization = Convert.ToString(row[1]);
			Member = Convert.ToString(row[2]);
			LastPolledAt = DateTime.SpecifyKind(DateTime.FromOADate(Convert.ToDouble(row[3])), DateTimeKind.Utc);
		}

		public string Instance { get; set; } = Exceptions.NotAvailable;

		public string Organization { get; set; }

		public string Member { get; set; }

		public DateTime LastPolledAt
		{
			get
			{
				return lastPolledAt;
			}

			set
			{
				if (value.Kind != DateTimeKind.Utc)
				{
					throw new ArgumentException("LastPolledAt must be in UTC.");
				}

				lastPolledAt = value;
			}
		}

		public static MemberOrganizationLinksTableRow FromPK(SLProtocol protocol, string pk)
		{
			var row = (object[])protocol.GetRow(Parameter.Memberorganizationlinks.tablePid, pk);
			if (row[0] == null)
			{
				return default;
			}

			return new MemberOrganizationLinksTableRow(row);
		}

		public object[] ToProtocolRow()
		{
			return new MemberorganizationlinksQActionRow
			{
				Memberorganizationlinksinstance_22001 = Instance,
				Memberorganizationlinksorganization_22002 = Organization,
				Memberorganizationlinksmember_22003 = Member,
				Memberorganizationlinkslastpolledatutc_21999 = LastPolledAt.ToOADate(),
			};
		}

		public void SaveToProtocol(SLProtocol protocol)
		{
			if (!protocol.Exists(Parameter.Memberorganizationlinks.tablePid, Instance))
			{
				protocol.AddRow(Parameter.Memberorganizationlinks.tablePid, ToProtocolRow());
			}
			else
			{
				protocol.SetRow(Parameter.Memberorganizationlinks.tablePid, Instance, ToProtocolRow());
			}
		}
	}

	public class MemberOrganizationLinksTable
	{
		private static MemberOrganizationLinksTable instance = new MemberOrganizationLinksTable();

		public MemberOrganizationLinksTable() { }

		public MemberOrganizationLinksTable(SLProtocol protocol)
		{
			uint[] memberOrganizationLinksIdx = new uint[]
			{
				Parameter.Memberorganizationlinks.Idx.memberorganizationlinksinstance_22001,
				Parameter.Memberorganizationlinks.Idx.memberorganizationlinksorganization_22002,
				Parameter.Memberorganizationlinks.Idx.memberorganizationlinksmember_22003,
				Parameter.Memberorganizationlinks.Idx.memberorganizationlinkslastpolledatutc_21999,
			};
			object[] memberorganizationlinks = (object[])protocol.NotifyProtocol((int)SLNetMessages.NotifyType.NT_GET_TABLE_COLUMNS, Parameter.Memberorganizationlinks.tablePid, memberOrganizationLinksIdx);
			object[] instance = (object[])memberorganizationlinks[0];
			object[] organization = (object[])memberorganizationlinks[1];
			object[] member = (object[])memberorganizationlinks[2];
			object[] lastPolledDateUtc = (object[])memberorganizationlinks[3];

			for (int i = 0; i < instance.Length; i++)
			{
				Rows.Add(new MemberOrganizationLinksTableRow(
				instance[i],
				organization[i],
				member[i],
				lastPolledDateUtc[i]));
			}
		}

		public List<MemberOrganizationLinksTableRow> Rows { get; set; } = new List<MemberOrganizationLinksTableRow>();

		public static MemberOrganizationLinksTable GetTable(SLProtocol protocol = null)
		{
			if (protocol is null)
			{
				return instance;
			}

			instance = new MemberOrganizationLinksTable(protocol);
			return instance;
		}

		public void SaveToProtocol(SLProtocol protocol, bool partial = false)
		{
			// Calculate the batch size, recommended 25000 cells max per fill array, divided by the number of columns.
			var batchSize = 25000 / 3;

			// If full then the first batch needs to be a SaveOption.Full.
			var first = !partial;
			if (!Rows.Any() && !partial)
			{
				protocol.ClearAllKeys(Parameter.Memberorganizationlinks.tablePid);
				return;
			}

			foreach (var batch in Rows.Select(x => x.ToProtocolRow()).Batch(batchSize))
			{
				if (first)
				{
					protocol.FillArray(Parameter.Memberorganizationlinks.tablePid, batch.ToList(), NotifyProtocol.SaveOption.Full);
				}
				else
				{
					protocol.FillArray(Parameter.Memberorganizationlinks.tablePid, batch.ToList(), NotifyProtocol.SaveOption.Partial);
				}
			}
		}

		public void DeleteRow(SLProtocol protocol, params string[] rowsToDelete)
		{
			if (rowsToDelete.Length <= 0)
				return;

			// Remove from DataMiner and local instance
			protocol.DeleteRow(Parameter.Memberorganizationlinks.tablePid, rowsToDelete);
			instance.Rows.RemoveAll(x => rowsToDelete.ToHashSet().Contains(x.Instance));
		}

		public void Cleanup(SLProtocol protocol, string organization)
		{
			var pollRow = PollManagerTable.GetTable(protocol).Rows.FirstOrDefault(r => r.RequestType == RequestType.Organizations_Teams);
			var toBeRemoved = Rows.Where(r => r.Organization == organization)
				.Where(r => r.LastPolledAt < pollRow.LastPolledUTCTime)
				.Select(r => r.Instance)
				.ToArray();

			DeleteRow(protocol, toBeRemoved);
		}
	}
}
