// <auto-generated code />
namespace Skyline.Protocol.PollManager
{
	using System.ComponentModel;

	public enum RequestType
	{
		[Description("Repositories/Repositories")] Repositories_Repositories = 201,
		[Description("Repositories/Issues")] Repository_Issues = 202,
		[Description("Repositories/Tags")] Repositories_Tags = 203,
		[Description("Repositories/Releases")] Repositories_Releases = 204,
		[Description("Repositories/Workflows")] Repositories_Workflows = 205,

		[Description("Organizations/User")] Organizations_User = 210,
		[Description("Organizations/Repositories")] Organizations_Repositories = 211,

		[Description("Repositories/Public Keys")] Repositories_PublicKey = 228,
	}
}