// <auto-generated code />
namespace QAction_1.PollManager
{
    using System.ComponentModel;

    public enum RequestType
    {
        [Description("Repositories/Repositories")] Repositories_Repositories = 0,
        [Description("Repositories/Issues")] Repository_Issues = 1,
        [Description("Repositories/Tags")] Repositories_Tags = 2,
        [Description("Repositories/Releases")] Repositories_Releases = 3,
    }
}