<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Company>Skyline Communications</Company>
    <Copyright>© Skyline Communications</Copyright>
    <AssemblyVersion>2025.0701.1339.30825</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Skyline.DataMiner.Dev.Protocol" Version="10.3.9" />
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties DisLinkId="" DisProjectType="qactionHelperProject" DisLinkedXmlFile="..\protocol.xml" />
    </VisualStudio>
  </ProjectExtensions>
</Project>