// <auto-generated>This is auto-generated code by json2csharp. Do not modify.</auto-generated>
namespace Skyline.Protocol.API.Content
{
	using System;
	using System.Collections.Generic;

	using Newtonsoft.Json;

	// Root myDeserializedClass = JsonConvert.DeserializeObject<PutRepositoryContentResponse>(myJsonResponse);
	public class PutRepositoryContentResponse
	{
		[JsonProperty("content")]
		public Content Content { get; set; }

		[JsonProperty("commit")]
		public Commit Commit { get; set; }
	}

	public class Author
	{
		[JsonProperty("date")]
		public DateTime Date { get; set; }

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("email")]
		public string Email { get; set; }
	}

	public class Commit
	{
		[JsonProperty("sha")]
		public string Sha { get; set; }

		[JsonProperty("node_id")]
		public string NodeId { get; set; }

		[JsonProperty("url")]
		public string Url { get; set; }

		[JsonProperty("html_url")]
		public string HtmlUrl { get; set; }

		[JsonProperty("author")]
		public Author Author { get; set; }

		[JsonProperty("committer")]
		public CommitterResponse Committer { get; set; }

		[JsonProperty("message")]
		public string Message { get; set; }

		[JsonProperty("tree")]
		public Tree Tree { get; set; }

		[JsonProperty("parents")]
		public List<Parent> Parents { get; set; }

		[JsonProperty("verification")]
		public Verification Verification { get; set; }
	}

	public class CommitterResponse
	{
		[JsonProperty("date")]
		public DateTime Date { get; set; }

		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("email")]
		public string Email { get; set; }
	}

	public class Content
	{
		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("path")]
		public string Path { get; set; }

		[JsonProperty("sha")]
		public string Sha { get; set; }

		[JsonProperty("size")]
		public int Size { get; set; }

		[JsonProperty("url")]
		public string Url { get; set; }

		[JsonProperty("html_url")]
		public string HtmlUrl { get; set; }

		[JsonProperty("git_url")]
		public string GitUrl { get; set; }

		[JsonProperty("download_url")]
		public string DownloadUrl { get; set; }

		[JsonProperty("type")]
		public string Type { get; set; }

		[JsonProperty("_links")]
		public Links Links { get; set; }
	}

	public class Links
	{
		[JsonProperty("self")]
		public string Self { get; set; }

		[JsonProperty("git")]
		public string Git { get; set; }

		[JsonProperty("html")]
		public string Html { get; set; }
	}

	public class Parent
	{
		[JsonProperty("url")]
		public string Url { get; set; }

		[JsonProperty("html_url")]
		public string HtmlUrl { get; set; }

		[JsonProperty("sha")]
		public string Sha { get; set; }
	}

	public class Tree
	{
		[JsonProperty("url")]
		public string Url { get; set; }

		[JsonProperty("sha")]
		public string Sha { get; set; }
	}

	public class Verification
	{
		[JsonProperty("verified")]
		public bool Verified { get; set; }

		[JsonProperty("reason")]
		public string Reason { get; set; }

		[JsonProperty("signature")]
		public object Signature { get; set; }

		[JsonProperty("payload")]
		public object Payload { get; set; }
	}


}
