// <auto-generated>This is auto-generated code by json2csharp. Do not modify.</auto-generated>
namespace Skyline.Protocol.API.Content
{
	using System;

	using Newtonsoft.Json;

	[Serializable]
	public class PutRepositoryContentRequest
	{
		[JsonProperty("message")]
		public string Message { get; set; }

		[JsonProperty("content")]
		public string Content { get; set; }

		[JsonProperty("branch", NullValueHandling = NullValueHandling.Ignore)]
		public string Branch { get; set; }

		[JsonProperty("sha", NullValueHandling = NullValueHandling.Ignore)]
		public string Sha { get; set; }

		[JsonProperty("committer", NullValueHandling = NullValueHandling.Ignore)]
		public CommitterRequest Committer { get; set; }
	}

	[Serializable]
	public class CommitterRequest
	{
		[JsonProperty("name")]
		public string Name { get; set; }

		[JsonProperty("email")]
		public string Email { get; set; }
	}
}
